#!/bin/bash -e
# ---
# RightScript Name: Initialise and mount additional volume
# Description: "Initialises and mounts an additional partitionless volume\r\n\r\nNote:
#   Will not reinitialise the volume if it's already mounted or it already has a filesystem
#   unless $ADD_VOLUME_REINITIALISE is true\r\n\r\nAuthor: Martin Baillie <martin.baillie@iag.com.au>"
# Inputs:
#   ADD_VOLUME_BLOCK_DEVICE:
#     Category: Additional Volume
#     Description: The block (special) device to initialise and mount, e.g. /dev/sdb.
#     Input Type: single
#     Required: true
#     Advanced: false
#     Default: text:/dev/xvdc
#     Possible Values:
#     - text:/dev/sdb
#     - text:/dev/sdc
#     - text:/dev/sdd
#     - text:/dev/xvdb
#     - text:/dev/xvdc
#     - text:/dev/xvdd
#     - text:/dev/xvdm
#   ADD_VOLUME_FS_OPTIONS:
#     Category: Additional Volume
#     Description: Additional options for mkfs.
#     Input Type: single
#     Required: true
#     Advanced: false
#     Default: blank
#   ADD_VOLUME_FS_TYPE:
#     Category: Additional Volume
#     Description: The filesystem type for the additional volume.
#     Input Type: single
#     Required: true
#     Advanced: false
#     Default: text:ext4
#     Possible Values:
#     - text:ext4
#     - text:ext3
#     - text:ext2
#     - text:xfs
#     - text:btrfs
#     - text:reiserfs
#     - text:ntfs
#     - text:bfs
#     - text:cramfs
#     - text:fat
#     - text:minix
#     - text:msdos
#     - text:vfat
#   ADD_VOLUME_INITIALISE:
#     Category: Additional Volume
#     Description: Whether or not to initialise the additional volume.
#     Input Type: single
#     Required: true
#     Advanced: false
#     Default: text:true
#     Possible Values:
#     - text:true
#     - text:false
#   ADD_VOLUME_MOUNT_OPTIONS:
#     Category: Additional Volume
#     Description: Mount options for the additional volume.
#     Input Type: single
#     Required: true
#     Advanced: false
#     Default: text:defaults,noatime
#   ADD_VOLUME_MOUNT_POINT:
#     Category: Additional Volume
#     Description: The mount point for the additional volume.
#     Input Type: single
#     Required: true
#     Advanced: false
#     Default: text:/mnt/data
#     Possible Values:
#     - text:/mnt/data
#     - text:/mnt
#     - text:/data
#     - text:/mnt/mysql-data
#     - text:/mnt/pgdata
#   ADD_VOLUME_REINITIALISE:
#     Category: Additional Volume
#     Description: Whether or not to re-initialise the volume if a filesystem already
#       exists.
#     Input Type: single
#     Required: true
#     Advanced: false
#     Default: text:false
# Attachments: []
# ...

# Description: Initialises and mounts an additional partitionless volume
# Author: Martin Baillie <martin.baillie@iag.com.au>
# Contributor: Chris Fordham <chris.fordham@industrieit.com>

# Note: Will not reinitialise the volume if it's already mounted or
# it already has a filesystem unless $ADD_VOLUME_REINITIALISE is true

# Inputs:
# $ADD_VOLUME_FS_TYPE
# $ADD_VOLUME_FS_OPTIONS
# $ADD_VOLUME_BLOCK_DEVICE
# $ADD_VOLUME_MOUNT_POINT
# $ADD_VOLUME_MOUNT_OPTIONS
# $ADD_VOLUME_INITIALISE
# $ADD_VOLUME_REINITIALISE

: "${ADD_VOLUME_FS_TYPE:=ext4}"
: "${ADD_VOLUME_FS_OPTIONS:=}"
: "${ADD_VOLUME_BLOCK_DEVICE:=/dev/sdc}"
: "${ADD_VOLUME_MOUNT_POINT:=/mnt/data}"
: "${ADD_VOLUME_MOUNT_OPTIONS:=defaults,noatime}"
: "${ADD_VOLUME_INITIALISE:=false}"
: "${ADD_VOLUME_REINITIALISE:=false}"

# exit gracefully if told to not initialise the volume
if [ "$ADD_VOLUME_INITIALISE" != 'true' ]; then
  echo '$ADD_VOLUME_INITIALISE not set to true, skipping.'
  exit 0
fi

# Install required tools:
# only xfs currently
case $ADD_VOLUME_FS_TYPE in
*xfs*)
  pkg=xfsprogs
  if type apt-get > /dev/null 2>&1; then
    sudo apt-get -y install "$pkg"
  else
    sudo yum -y install "$pkg"
  fi
  ;;  
esac

# Sanity checks:
if [ ! -b "${ADD_VOLUME_BLOCK_DEVICE}" ]; then
    echo "ERROR: block device ${ADD_VOLUME_BLOCK_DEVICE} not attached"
    exit 1
fi

# Idempotency:
if mount | grep "${ADD_VOLUME_BLOCK_DEVICE}" > /dev/null; then
    echo "Volume ${ADD_VOLUME_BLOCK_DEVICE} is currently mounted"

    if [ "${ADD_VOLUME_REINITIALISE}" != "true" ]; then
        echo '$ADD_VOLUME_REINITIALISE != true. Nothing to do here'
        exit 0
    fi
    echo '$ADD_VOLUME_REINITIALISE == true. Unmounting and reinitialising'
    sudo umount -f "${ADD_VOLUME_BLOCK_DEVICE}"
fi

# Initialisation:
if [ "${ADD_VOLUME_REINITIALISE}" = "true" ] ||
    ! sudo blkid | grep "${ADD_VOLUME_BLOCK_DEVICE}" | grep TYPE > /dev/null; then
    echo "Wiping block device ${ADD_VOLUME_BLOCK_DEVICE}"
    sudo wipefs -a "${ADD_VOLUME_BLOCK_DEVICE}"

    echo "Creating ${ADD_VOLUME_FS_TYPE} filesystem on ${ADD_VOLUME_BLOCK_DEVICE}"
    sudo mkfs."${ADD_VOLUME_FS_TYPE}" ${ADD_VOLUME_FS_OPTIONS} "${ADD_VOLUME_BLOCK_DEVICE}"
else
    echo "Not (re-)initialising volume. Continuing to ensure it is correctly mounted"
fi

# Mounting:
if [ -e "${ADD_VOLUME_MOUNT_POINT}" ]; then
    echo "Mount point exists. Removing"
    sudo rm -rf "${ADD_VOLUME_MOUNT_POINT}"
fi
echo "Recreating mount point"
sudo mkdir -p "${ADD_VOLUME_MOUNT_POINT}"

if ! grep "${ADD_VOLUME_BLOCK_DEVICE}" /etc/fstab > /dev/null; then
    echo "Editing fstab to automount ${ADD_VOLUME_BLOCK_DEVICE} at ${ADD_VOLUME_MOUNT_POINT}"
    echo "${ADD_VOLUME_BLOCK_DEVICE} ${ADD_VOLUME_MOUNT_POINT} ${ADD_VOLUME_FS_TYPE} " \
        "${ADD_VOLUME_MOUNT_OPTIONS} 0 0" | sudo tee -a /etc/fstab
fi

echo "Mounting ${ADD_VOLUME_BLOCK_DEVICE} at ${ADD_VOLUME_MOUNT_POINT}"
sudo mount "${ADD_VOLUME_MOUNT_POINT}"

echo "Done."
