#!/usr/bin/sudo /bin/bash
# ---
# RightScript Name: SYS docker storage to /mnt
# Description: Bind-mounts /var/lib/docker to /mnt/docker in order to make use of ephemeral
#   storage.
# Inputs: {}
# Attachments: []
# ...

set -e

if [ ! -d /var/lib/docker ]
then
  echo "Redirecting Docker local storage to /mnt"
  mkdir /mnt/docker
  chmod 0700 /mnt/docker
  mkdir /var/lib/docker
  chmod 0700 /var/lib/docker
  mount --bind /mnt/docker /var/lib/docker
fi
