#! /bin/bash -e
# ---
# RightScript Name: Set system ulimits
# Description: Sets/prints the ulimits on the system.
# Inputs:
#   ULIMITS:
#     Category: System
#     Description: A semi-colon separated list of limits to set in /etc/security/limits.conf
#       e.g. *,hard,nproc,32768;*,hard,memlock,1048576
#     Input Type: single
#     Required: false
#     Advanced: false
#   ULIMITS_REBOOT:
#     Category: System
#     Description: Whether to reboot after setting the ulimits.
#     Input Type: single
#     Required: true
#     Advanced: false
#     Default: text:true
#     Possible Values:
#     - text:true
#     - text:false
#   ULIMITS_SET:
#     Category: System
#     Description: Whether to set the ulimits provided.
#     Input Type: single
#     Required: true
#     Advanced: false
#     Default: text:true
#     Possible Values:
#     - text:true
#     - text:false
# Attachments: []
# ...

# Set system ulimits

# Description: Sets/prints the ulimits on the system.
#
# Author: Chris Fordham <chris.fordham@industrieit.com>

# Inputs:
# $ULIMITS          A semi-colon separated list of limits to set in /etc/security/limits.conf
#                   e.g. *,hard,nproc,32768;*,hard,memlock,1048576
# $ULIMITS_SET      Whether to set the ulimits provided
# $ULIMITS_REBOOT   Whether to reboot after setting the ulimits

: "${ULIMITS:=}"
: "${ULIMITS_REBOOT:=true}"
: "${ULIMITS_SET}:=true}"

if [ ! "$ULIMITS_SET" = 'true' ]; then
  echo '$ULIMITS_SET not set to true, skipping.'
  exit 0
fi

if [ -z "$ULIMITS" ]; then
  echo 'No ulimits provided, skipping.'
  exit 0
fi

ulimits=(${ULIMITS//;/ })

# display system ulimits
echo 'Current global ulimits:'
echo '--'
ulimit -a   # see all the kernel parameters
echo '--'
echo

if [ -e /etc/security/limits.d ]; then
  limit_file=/etc/security/limits.d/extra.conf
else
  limit_file=/etc/security/limits.conf
fi
sudo touch "$limit_file"
echo "Using $limit_file"

# make a copy of the existing file to see if we need to reboot at end
cp "$limit_file" /tmp/limit.conf.old

# remove the end of line line
sudo sed -i '/# End of file/d' "$limit_file"

for ulimit in "${ulimits[@]}"
do
  ulimit=$(echo "$ulimit" | tr , '\t\t')

  if ! grep "$ulimit" "$limit_file"; then
    echo "$ulimit" | sudo tee -a "$limit_file"
  fi
done

# add the end of line line
sudo sed -i '/^$/d' "$limit_file"
echo "" | sudo tee -a "$limit_file"
echo "# End of file" | sudo tee -a "$limit_file"

if [ "$ULIMITS_REBOOT" = true ]; then
  if ! diff /tmp/limit.conf.old "$limit_file"; then
    echo 'Backgrounding reboot command (60 seconds)'
    exec $(sleep 60; sudo reboot &)&
  else
    echo 'Skipping reboot as there is no change to the limits file.'
    exit 0
  fi
else
  echo 'IMPORTANT: A system reboot is required to effect changes.'
fi

# display the new ulimits file
echo "New ulimits file ($limit_file):"
echo '--'
cat "$limit_file"
echo '--'
echo

echo 'Done.'
